### ISSUE TITLE
Recommendations for setup on multiple devices

### ISSUE THREAD

**Issue by StevenBlack** [keys-pub/keys#10]
Hi 👋   Nice project!

The docs aren't clear on this question: how do you recommend setting up multiple devices to use the same private key?  Or is that a no-no?

**Comment by gabriel** [comment]
Great question. If you need to use the app on multiple machines, you can copy the private key to other devices by using `keys export` and `keys import` (or the desktop app Export/Import).

In the future, possibly, there will be a way to associate multiple keys to an identity but currently there is a 1-1 relationship, which means currently you can only using a single key at a time.

**Comment by gabriel** [comment]
I'll keep this issue open, util I get a FAQ going. Thanks for your question and feedback.

**Comment by StevenBlack** [comment]
Thanks @gabriel this works perfectly in the App UI.

**Comment by werediver** [comment]
> In the future, possibly, there will be a way to associate multiple keys to an identity but currently there is a 1-1 relationship, which means currently you can only use a single key at a time.

I'd say this is worth tracking in a dedicated ticket. To me and, I believe, to many of people (judging by the Hacker News discussion pages on keys.pub and keybase.io) that would be a crucial upgrade.

**Comment by gabriel** [comment]
The latest release has an experimental feature called Vault which provides backup and sync (if enabled).
I've started some really basic documentation at https://keys.pub/docs/specs/vault.html, will be adding to it more in the next few days.

The multiple key issue is mentioned here, https://github.com/keys-pub/keys/issues/41, maybe continue that discussion there?
