### ISSUE TITLE
Error on MacOS catalina

### ISSUE THREAD

**Issue by danielepolencic** [keys-pub/keys#17]
When I open the app for the first time I see:

<img width="920" alt="Screenshot 2020-05-04 at 20 17 31" src="https://user-images.githubusercontent.com/1130499/80965106-98c21d00-8e44-11ea-84ec-e4f53efa0c16.png">

Error:

```
Oops, exec error: Error: Command failed: /Volumes/Keys 0.0.38/Keys.app/Contents/Resources/bin/keys start --from=app
/bin/sh: /Volumes/Keys: No such file or directory
```

OS: Catalina 10.15.3
Keys-0.0.38

**Comment by gabriel** [comment]
Oh it might not support being run straight from the dmg yet. You can work around this by copying to Applications folder until a fix is out.

**Comment by danielepolencic** [comment]
That fixed the problem.

This issue is resolved for me, but should I leave it open?

**Comment by gabriel** [comment]
Yeah, leave open.

**Comment by gabriel** [comment]
https://github.com/keys-pub/app/commit/b344f12de4fdcfcf23ff7e645c11ad8a81439b48

See  https://github.com/keys-pub/app/releases/tag/v0.0.39-rc1
