### ISSUE TITLE
Windows naming conflict

### ISSUE THREAD

**Issue by 1nfdev** [keys-pub/keys#18]
Windows support legacy DOS command `keys`.

I didn't install keys for CLI, so I don't know what shall happen if install.
Just keep that in mind. Perhaps it may confuse or complicate writing cross-platform scripts.

I didn't find information on the DOS command `keys` on the Internet. I got the information from a message in the console, through `keys /?`, After the message `keys` -> "Keys mode is disabled."

**Comment by 1nfdev** [comment]
Move issue to cli client.

**Comment by gabriel** [comment]
Yeah this was an oversight on my part, but not sure if it's a big problem?

It is possible in command prompt to specify the full path to the executable.

For normal command line usage, do most people still use the command prompt?
On windows install we could also include keysp.exe or some alternative if it is a problem.

**Comment by gabriel** [comment]
Thanks for bring this up but I'm going to close this.
