### ISSUE TITLE
https link method should use `.well-known`

### ISSUE THREAD

**Issue by devsnek** [keys-pub/keys#21]
The url should be `https://example.com/.well-known/keyspub.txt`. See https://tools.ietf.org/html/rfc8615 and https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml and maybe https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers

**Comment by gabriel** [comment]
My gut reaction is worrying that somehow a hacker could get access to that directory more easily, but that doesn't seem right.

I could whitelist that location so both are valid?
https://example.com/keyspub.txt
https://example.com/.well-known/keyspub.txt

**Comment by devsnek** [comment]
Both also works

**Comment by prusnak** [comment]
I am not sure whether GitHub pages serve folders starting with a dot.

**Comment by devsnek** [comment]
It can using a `_config.yml`:

```yml
include:
  - ".well-known"
```

**Comment by gabriel** [comment]
This will land in the next version, see https://github.com/keys-pub/keys/pull/49

**Comment by gabriel** [comment]
Fixed in 0.0.47.
![Uploading 2020-06-03 at 5.36 PM.png…]()

**Comment by nkoehring** [comment]
I have that version (at least my version suggests to use .well-known) but it didn't find the file (literally saying 404). Moving it to the root folder worked.

**Comment by gabriel** [comment]
Oops, this is not working. Re-opening.

Thanks for reporting the issue.

**Comment by gabriel** [comment]
Fixed in https://github.com/keys-pub/app/commit/73cf02561b7055dd8e2ebac5d33a1d8688f3dfc6. Will be in next release.
