### ISSUE TITLE
Migrate from Keybase Guide

### ISSUE THREAD

**Issue by sandstrom** [keys-pub/keys#22]
If you're quick you could add a "migrate from Keybase" blog post or section on your website, and post a comment in either of these three threads:

https://news.ycombinator.com/item?id=23103386
https://news.ycombinator.com/item?id=23104702
https://news.ycombinator.com/item?id=23102430

Could help drive adoption!

**Comment by sandstrom** [comment]
friendly ping @gabriel 😄

**Comment by gabriel** [comment]
Thanks for the interest. I'm friends with Keybase so... am really happy for them.

**Comment by sandstrom** [comment]
@gabriel Yeah, I know 😄 I saw that in your profile.

I've been a happy Keybase user for several years. But their blog post basically says that there is a pretty big risk that keybase will be deprecated or abandoned eventually.

As evident from the HN-threads above some people are looking for alternatives and providing comparison guides and migration guides is very common, among all types of software.

Could be a good idea for keys.pub too
