### ISSUE TITLE
Github usernames can be uppercase

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [keys-pub/keys#36]
When adding a gist to verify one's github account, the keys.pub application requires a lowercase username. This isn't a large issue except that when keys.pub tries to verify the username and gist, the usernames don't match because the real one is uppercase. 

Screenshots below

![image](https://user-images.githubusercontent.com/28550422/81477760-10929d80-91df-11ea-8465-a4ac72ea0409.png)

After changing my username to lowercase and creating the gist, I get this error while verifying. 

![image](https://user-images.githubusercontent.com/28550422/81477798-459ef000-91df-11ea-881a-5e0db97a5bab.png)

This is not a critical issue since you can make the name in the url lowercase and it will succeed, but it certainly is not great UX.

**Comment by gabriel** [comment]
Yeah this is a known issue, I think a new build is going out today.
Thanks for reporting the issue.

**Comment by gabriel** [comment]
Fixed in v0.0.43 via https://github.com/keys-pub/keys/pull/25.
