### ISSUE TITLE
Security Issue with too many created signatures

### ISSUE THREAD

**Issue by fix** [keys-pub/keys#88]
I love this app, tanks for developing it, it is awesome.

While signing a message in the app, it update the signature for every key typed! While cool UX wise, i think this a dangerous practice as it creates hundreds/thousands of useless signatures. Plus it gives the user te impression that signatures are cheap and thus not sound.

Same for encryption

**Comment by gabriel** [comment]
The speed of the signatures/encryption doesn't affect the security at all, but yeah I see how the speed of it could give the impression that it's not doing "work". But I think the idea might be to change that impression?

Thanks for the feedback!
